[package]
name = "mostr"
description = "A nested task chat, powered by nostr."
repository  = "https://forge.ftt.gmbh/janek/mostr"
readme = "README.md"
license = "GPL 3.0"
authors = ["melonion"]
version = "0.9.1"
rust-version = "1.82"
edition = "2021"
default-run = "mostr"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nostr-sdk = { version = "0.38", features = ["ndb", "nip49"] }
# Basics
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
regex = "1.11"
# System
log = "0.4"
env_logger = "0.11"
colog = "1.3"
colored = "2.2"
rustyline = { git = "https://github.com/xeruf/rustyline", rev = "5364854" }
# OS-Specific Abstractions
keyring = "3"
directories = "5.0"
whoami = "1.5"
# slint = "1.8"
# Application Utils
itertools = "0.12"
chrono = "0.4"
parse_datetime = "0.5"
interim = { version = "0.1", features = ["chrono"] }

[dev-dependencies]
mostr = { path = ".", default-features = false }

[features]
default = ["persistence"]
persistence = ["keyring/apple-native", "keyring/windows-native", "keyring/linux-native-sync-persistent", "keyring/crypto-rust"]
